app:
    resource: '@AppBundle/Controller/'
    type: annotation

api:
    resource: "@AppBundle/Controller/Api"
    host:     "api.{domain}"

back:
    resource: "@AppBundle/Controller/Back"
    host:     "back.{domain}"
