# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
       user_db:
           entity:
               class: AppBundle:User
               property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern : ^/
            provider: user_db
            form_login :
                login_path: login
                check_path: login
                default_target_path: redirection
                always_use_default_target_path: true
            logout:
                path: logout
                target: /
